### PR TITLE
Description string updates

### PR DESCRIPTION
**Pull request by terracoda**
@jessegreenberg, I do not see any conflicts with these description changes.
My commits are small and I think easy to understand.
Please check this pull request when you have a moment.

### CODE REVIEW

**Comment by terracoda** [comment]
@jessegreenberg, this is my pull request, could you give me a quick indication when you might be able to review it? Or if it needs to be reviewed.

**Comment by terracoda** [comment]
@zepumph, would you be able to review this pull request? There are no conflicts as far as I can tell.

**Comment by terracoda** [comment]
Thanks @zepumph, I'll merge pull request by pressing the green button :-)

**Comment by terracoda** [comment]
@jessegreenberg and @zepumph, I merged and deleted the branch.

**Comment by terracoda** [comment]
@jessegreenberg, I think this merge request can be closed. It might be a bit stale by now.

**Comment by terracoda** [comment]
@jessegreenberg, sorry, I don't know how to close a merge request.

**Comment by jessegreenberg** [comment]
Looks like it is good to go @terracoda, github says there are 0 pull requests waiting, and this one is considered  "merged" already.  I guess these don't "close". But this PR is showing up in this closed list:
https://github.com/phetsims/balloons-and-static-electricity/pulls?q=is%3Apr+is%3Aclosed

**Comment by terracoda** [comment]
Thanks for the explanation and link to the merge.

**Pull request merged**
